-- Example Fizzia portfolio projects.
-- Run after supabase/fizzia_schema.sql if you want starter projects on the landing.

insert into public.portfolio_projects (
  slug,
  title,
  client_name,
  industry,
  province,
  city,
  summary,
  challenge,
  solution,
  results,
  website_url,
  sort_order,
  is_featured,
  is_published,
  completed_at
) values
  (
    'zaphiro-studio',
    'Zaphiro Studio',
    'Zaphiro Studio',
    'Servicios profesionales',
    'Pichincha',
    'Quito',
    'Portafolio profesional con reservas y catalogo digital.',
    'El negocio necesitaba presentar servicios y recibir contactos sin depender solo de redes sociales.',
    'Creamos una web clara, responsive y preparada para captar solicitudes.',
    'Mayor confianza comercial y canal directo para nuevos clientes.',
    'https://example.com',
    10,
    true,
    true,
    current_date
  ),
  (
    'dashboard-comercial',
    'Dashboard Comercial',
    'Fizzia Demo',
    'SaaS',
    'Guayas',
    'Guayaquil',
    'Panel de ventas, clientes y metricas para toma de decisiones.',
    'El equipo necesitaba ver actividad comercial en un solo lugar.',
    'Disenamos un dashboard con metricas, clientes, ventas y seguimiento.',
    'Informacion mas ordenada y decisiones mas rapidas.',
    'https://example.com',
    20,
    true,
    true,
    current_date
  ),
  (
    'sabores-que-encantan',
    'Sabores que encantan',
    'Sabores que encantan',
    'Gastronomia',
    'Azuay',
    'Cuenca',
    'Landing y menu digital para restaurante con enfoque en conversion.',
    'El restaurante queria mostrar su oferta y recibir pedidos de forma mas directa.',
    'Creamos una experiencia visual con menu digital, llamados a la accion y contacto rapido.',
    'Mejor presentacion del negocio y flujo de pedidos mas claro.',
    'https://example.com',
    30,
    false,
    true,
    current_date
  )
on conflict (slug) do update
set title = excluded.title,
    client_name = excluded.client_name,
    industry = excluded.industry,
    province = excluded.province,
    city = excluded.city,
    summary = excluded.summary,
    challenge = excluded.challenge,
    solution = excluded.solution,
    results = excluded.results,
    website_url = excluded.website_url,
    sort_order = excluded.sort_order,
    is_featured = excluded.is_featured,
    is_published = excluded.is_published,
    completed_at = excluded.completed_at,
    updated_at = now();
